server {
    listen 80;
    server_name localhost;

    # Redirection du Front-End
    location / {
        proxy_pass http://jardin_node:5173; # Redirige vers le conteneur Node
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Redirection du Back-End
    location ~ ^/(api|secu|_profiler|_wdt) {
        root /var/www/html/public;
        try_files $uri /index.php$is_args$args;
    }

    # Traitement des fichiers PHP
    location ~ ^/index\.php(/|$) {
        root /var/www/html/public;
        fastcgi_pass php:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
        internal;
    }

    # sécurité accès fichiers .php
    location ~ \.php$ {
        return 404;
    }

    error_log /var/log/nginx/project_error.log;
    access_log /var/log/nginx/project_access.log;
}
