server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;

    # 1. Redirection du Front-End (Par défaut)
    location / {
        proxy_pass http://node:5173; # Remplace 'node' par le nom de ton conteneur
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # 2. Si on demande un fichier CSS/JS qui existe dans le dossier public de Symfony
    location /bundles {
        try_files $uri =404;
    }

    # 3. Redirection du Back-End (API)
    location ~ ^/(api|secu|_profiler|_wdt) {
        try_files $uri /index.php$is_args$args;
    }

    # 4. Traitement des fichiers PHP par PHP-FPM
    location ~ ^/index\.php(/|$) {
        fastcgi_pass php:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
        internal;
    }

    # 5. Sécurité : accès fichiers .php
    location ~ \.php$ {
        return 404;
    }

    error_log /var/log/nginx/project_error.log;
    access_log /var/log/nginx/project_access.log;
}
